vich_uploader:
    db_driver: orm

    mappings:
        user_images:
            uri_prefix: /images/userimg
            upload_destination: '%kernel.project_dir%/public/images/userimg'
            namer : Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
